Repository microsoft/UVAtlas, pull requests merged in 2023-12, with the labels that each got.

#133 Have CMake generate pkg-config file for library
  CMakeLists.txt
  build/JoinPaths.cmake
  build/UVAtlas.pc.in
Labels: enhancement

#132 Fix warnings generated by clang
  CMakeLists.txt
  UVAtlas/isochart/UVAtlas.cpp
  UVAtlas/isochart/imtcomputation.cpp
  UVAtlas/isochart/isochartengine.cpp
  UVAtlas/isochart/isochartmesh.cpp
  UVAtlas/isochart/meshoptimizestretch.cpp
  UVAtlas/pch.h
  UVAtlasTool/Mesh.cpp
  UVAtlasTool/MeshOBJ.cpp
  UVAtlasTool/UVAtlas.cpp
Labels: conformance

#134 Fix build breaks for DEBUG builds
  UVAtlas/isochart/UVAtlas.cpp
  UVAtlas/isochart/imtcomputation.cpp
  UVAtlas/isochart/isochartengine.cpp
  UVAtlas/isochart/meshoptimizestretch.cpp
  UVAtlas/pch.h
  build/UVAtlas-GitHub-Test-Dev17.yml
  build/UVAtlas-GitHub-Test.yml
Labels: bug
